spring:
  elasticsearch:
    host: ${ES_HOST}
    port: ${ES_PORT}

app:
  board_base_url: ${BOARD_BASE_URL}
  target_date: ${TARGET_DATE}
  web_driver_path: ${WEB_DRIVER_PATH}
  es_index_name: ${ES_INDEX_NAME}
  politeness: ${POLITENESS}

logging:
  level:
    org.example.community.crawler: ${LOGGING_LEVEL}