spring:
  elasticsearch:
    uris: "http://localhost:9200"
    host: "localhost"
    port: "9200"

app:
  board_base_url: "https://gall.dcinside.com/board/lists/?id=rlike"
  target_date: "2022-03-25"
  web_driver_path: "C:\\Program Files\\chromedriver_win32\\chromedriver.exe"
  es_index_name: "my-index-1"

logging:
  level:
    org.example.community.crawler: "info"

