spring:
  elasticsearch:
    host: "localhost"
    port: "9200"

app:
  board_base_url: "https://gall.dcinside.com/board/lists?id=rlike" # https://gall.dcinside.com/board/lists?id=rlike https://gall.dcinside.com/mgallery/board/lists?id=mf
  target_date: "2022-05-15"
  web_driver_path: "C:\\Program Files\\chrome_driver_100\\chromedriver.exe"
  es_index_name: "dc-content-loglike"

logging:
  level:
    org.example.community.crawler: "info"